netfilter/xt_hashlimit: Fix build error caused by 64bit division
64-bit division causes build/link errors on 32-bit architectures. It
prints out error messages like:

  ERROR: "__aeabi_uldivmod" [net/netfilter/xt_hashlimit.ko] undefined!

The value of avg passed through by userspace in BYTE mode cannot exceed
U32_MAX. Which means 64bit division in user2rate_bytes is unnecessary.
To fix this I have changed the type of param 'user' to u32.

Since anything greater than U32_MAX is an invalid input we error out in
hashlimit_mt_check_common() when this is the case.

Signed-off-by: Vishwanath Pai <vpai@akamai.com>
Cc: Linus Torvalds <torvalds@linux-foundation.org>
Cc: Peter Zijlstra <peterz@infradead.org>
Cc: Thomas Gleixner <tglx@linutronix.de>
Cc: akpm@linux-foundation.org
Cc: andrew.cooper3@citrix.com
Cc: arnd@arndb.de
Cc: boris.ostrovsky@oracle.com
Cc: bp@alien8.de
Cc: brgerst@gmail.com
Cc: davem@davemloft.net
Cc: fw@strlen.de
Cc: ilubashe@akamai.com
Cc: jgross@suse.com
Cc: johunt@akamai.com
Cc: kadlec@blackhole.kfki.hu
Cc: keescook@chromium.org
Cc: luto@kernel.org
Cc: netdev@vger.kernel.org
Cc: netfilter-devel@vger.kernel.org
Cc: pablo@netfilter.org
Cc: pai.vishwain@gmail.com
Fixes: bea74641e378 ("netfilter: xt_hashlimit: add rate match mode")
Link: http://lkml.kernel.org/r/1504849138-17427-1-git-send-email-vpai@akamai.com
Signed-off-by: Ingo Molnar <mingo@kernel.org>