perf/probe: Fix wrong address verification
Since there are some DIE which has only ranges instead of the
combination of entrypc/highpc, address verification must use
dwarf_haspc() instead of dwarf_entrypc/dwarf_highpc.

Also, the ranges only DIE will have a partial code in different
section (e.g. unlikely code will be in text.unlikely as "FUNC.cold"
symbol). In that case, we can not use dwarf_entrypc() or
die_entrypc(), because the offset from original DIE can be
a minus value.

Instead, this simply gets the symbol and offset from symtab.

Without this patch;
  # tools/perf/perf probe -D clear_tasks_mm_cpumask:1
  Failed to get entry address of clear_tasks_mm_cpumask
    Error: Failed to add events.

And with this patch
  # perf probe -D clear_tasks_mm_cpumask:1
  p:probe/clear_tasks_mm_cpumask _text+632816
  p:probe/clear_tasks_mm_cpumask_1 _text+632821
  p:probe/clear_tasks_mm_cpumask_2 _text+632830

Reported-by: Arnaldo Carvalho de Melo <acme@kernel.org>
Fixes: 576b523721b7 ("perf probe: Fix probing symbols with optimization suffix")
Signed-off-by: Masami Hiramatsu <mhiramat@kernel.org>