perf probe: Do not require root to show vars in user binaries
Do not require root privilege to show available variables in
user binaries. Since perf probe always tries to access vmlinux
for --vars option even if user passes -x option.

Without this patch (by normal user):
  ----
  $ perf probe -x ./perf -V add_cmdname
  Failed to init vmlinux path.
    Error: Failed to show vars.
  ----

With this patch:
  ----
  $ perf probe -x ./perf -V add_cmdname
  Available variables at add_cmdname
          @<perf_unknown_cmd_config+144>
                  (No matched variables)
          @<list_commands_in_dir+160>
                  (No matched variables)
          @<add_cmdname+0>
                  char*   name
                  size_t  len
                  struct cmdnames*        cmds
  ----

Signed-off-by: Masami Hiramatsu <masami.hiramatsu@gmail.com>